<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="/">
    <span>
      <xsl:comment>This file is automatically generated.  Do not edit.</xsl:comment>
      <xsl:apply-templates/>
    </span>
  </xsl:template>

  <xsl:template match="quotation">
   <xsl:element name="p">
     <xsl:for-each select="text()">
       <xsl:copy/>
     </xsl:for-each>
   </xsl:element>

   <xsl:apply-templates select = "author | source"/>
  </xsl:template>

  <xsl:template match="author">
   <xsl:element name="p">
        <xsl:attribute name="class">author</xsl:attribute>
	<xsl:apply-templates />
   </xsl:element>
  </xsl:template>

  <xsl:template match="source">
   <xsl:element name="p">
        <xsl:attribute name="class">source</xsl:attribute>
	<xsl:apply-templates />
   </xsl:element>
  </xsl:template>

</xsl:stylesheet>
